# Application settings
app:
  name: "Chip8"

# Application logging configuration
logger:
  # Enable or disable logging.
  enable: true
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: true
  # Log level, options: trace, debug, info, warn or error.
  level: info
  # Define the logging format. options: compact, pretty or json
  format: compact
  # By default the logger has filtering only logs that came from your code or logs that came from loco framework. to see all third party libraries
  # Uncomment the line below to override to see all third party libraries you can enable this config and override the logger filters.
  # override_filter: trace

# Emulator settings configuration
chip8:
  scale: 10
  cycles_per_frame: 60
  bg_color:
    r: 0
    g: 0
    b: 0
    a: 255
  pixel_color:
    r: 255
    g: 255
    b: 255
    a: 255
  default_ch8_folder: "roms"
  st_equals_buzzer: true
  bit_shift_instructions_use_vy: false
  store_read_instructions_change_i: true
