# Application logging configuration
logger:
  # Enable or disable logging.
  enable: true
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: true
  # Log level, options: trace, debug, info, warn or error.
  level: info
  # Define the logging format. options: compact, pretty or json
  format: compact
  # By default, the logger has filtering only logs that came from your code or logs that came from loco framework. to see all third party libraries
  # Uncomment the line below to override to see all third party libraries you can enable this config and override the logger filters.
  # override_filter: trace

# Emulator settings configuration
chip8:
  # The amount of scaling done on the video resolution.
  # The internal video resolution (64x32) is multiplied by this value.
  # Default=10
  # Min=1
  # Max=20
  scale: 10

  # The amount of instruction cycles per rendered frame.
  # The engine will try to render the frames at 60hz.
  # Default=20
  # Min=1
  # Max=99999
  cycles_per_frame: 20

  # The color of the background (R,G,B format, 0 to 255).
  # Default=0,0,0 (BLACK)
  bg_color: "0,0,0"

  # The color of the pixels (R,G,B format, 0 to 255).
  # Default=255,255,255 (WHITE)
  pixel_color: "255,255,255"

  # The default folder where the CH8 (ROM) files are located.
  # It should be relative to the emulator's executable.
  # Default=ch8
  default_ch8_folder: "ch8"

  # The buzzer's original behavior is to sound (or not) based on the ST register's value.
  # Default=false
  st_equals_buzzer: false

  # The bit shift instructions SHR (8XY6) and SHL (8XYE) may be used differently by some games.
  # Default=true
  bit_shift_instructions_use_vy: true

  # The store (FX55) and read (FX65) instructions behavior regarding the register I.
  # Default=true
  store_read_instructions_change_i: true
